version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/var/www
    environment:
      - "REDIS_HOST=redis"

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"